### ISSUE TITLE
4WD different wheels speed

### ISSUE THREAD

**Issue by MarosMotaj** [larsmm/hoverboard-firmware-hack-FOC-bbcar#1]
"System"
- VARIANT: UART
- CONTROL TYPE: RC
-RC platform,

Hi,

Please, I am making 4WD RC platform with two boards. All works, but wheels on first board are spinning faster than on the second board. Can you help me? what I have to do?... thanks :)

**I have tried:**
I am using ESP32 hardware TX2 serial port, for both boards. Because I was thinking that the problem is in TX signal, but that problem is still ongoing.

**Comment by larsmm** [comment]
You are using the wrong repo for your task. This repo is for this specific vehicle (toy car to sit on controlled by potis). Use this repo instead: https://github.com/EFeru/hoverboard-firmware-hack-FOC

**Comment by MarosMotaj** [comment]
Ok, Thank you :) I solve it long time ago, I build 6x6 using 3 Hwboards
