### ISSUE TITLE
Dual input control problem

### ISSUE THREAD

**Issue by Mrsunhao1991** [larsmm/hoverboard-firmware-hack-FOC-bbcar#2]
### Your System
- VARIANT:bbcar
- CONTROL TYPE:adc  and pwm
- CONTROL MODE:
- What is your application?
    - 
The long control line on the left is used to connect two pedals, the short control line on the right is divided into two channels for connecting PWM remote control receiver, the green line is used to control forward and backward, and the blue line is used to control the input mode is ADC or PWM! Because I plan to improve the buggy for my child, considering that he can not drive by himself, so HE needs a PWM input! I'm new to this, thanks for your guidance!

**Before asking a question** see if it is already answered in:
* [Wiki pages](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki)

**Indicate what you have tried:**
If applicable, indicate what you tried that _doesn't_ work:

```c
input1[inIdx].raw = adc_buffer.l_rx2;
input2[inIdx].raw = adc_buffer.l_tx2
```

**Comment by larsmm** [comment]
It is not an easy task to implement rc control input to override the poti input. Sorry, I can not help you on this.
