### ISSUE TITLE
Wrong pot ouput, serial debuging.

### ISSUE THREAD

**Issue by CobraXLazer** [larsmm/hoverboard-firmware-hack-FOC-bbcar#3]
Hi

I got some problem with the new firmware!

Have used your old BBCAR firmware and it worked fine with the pots as input on the right cable, and now with thenew firmware the pots are showing up at BatADC and TempADC when i looking at the serial output, they change when turning the pots instead!

The "ini1 and ini2" should change to the pots but they change "BatADC and TempADC" in the serial output.

Any help would be good:) 

So i cant control my motor!

BTW loved the first firmware:)

**Comment by Candas1** [comment]
Hi @larsmm,

Someone once mentioned in the group that this issue could be related to the use of a that particular version of gcc [here](https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar/blob/bb8a506f4ff62aeeafb56e6b481d03f529ae4130/platformio.ini#L226)

**Comment by larsmm** [comment]
Oh, sorry, I have not seen your issue for such a long time!

I had no special reason for using a newer gcc version. I thought: newer == less bugs == better. I am compiling with these settings in windows in vscode + platformio and it is working fine. @CobraXLazer try to remove "@ >=1.90301.200702" in [this line](https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar/blob/bb8a506f4ff62aeeafb56e6b481d03f529ae4130/platformio.ini#L226) and try again.

**Comment by LONG-9527** [comment]
@larsmm After the firmware is brushed, the boot wheel rotates automatically, and there are two continuous drips. The pedals can't be calibrated.

**Comment by LONG-9527** [comment]
@Candas1

**Comment by LONG-9527** [comment]
![f552ad88cf438765963626bf3ca69f5](https://user-images.githubusercontent.com/127329914/224047426-38aa5a46-a5a9-48b9-9dbf-3dc1a3ab44ce.png)

**Comment by larsmm** [comment]
@LONG-9527 You are posting in the wrong issue of the wrong project!

https://github.com/larsmm/hoverboard-firmware-hack-bbcar/issues/6

**Comment by larsmm** [comment]
In version 1.100301.220327 of toolchain-gccarmnoneeabi package the adcs switched positions. In version 1.90301.200702 it is working like expected. There must be a serious problem in the code.

It is fixed in my newest commit.
