### ISSUE TITLE
Emergency Stop

### ISSUE THREAD

**Issue by charlesrg** [larsmm/hoverboard-firmware-hack-FOC-bbcar#4]
What would you use for emergency stop ? Would it be enough to just pull the battery out with a relay or disconnect switch ?

**Comment by larsmm** [comment]
It is not a good idea to pull the battery out. If you are fast and especially in field weakening mode very high voltages will be induced back from the motors and will destroy your board. And you will not be able to break without the battery.

The easiest way is to pull the forward-poti to ground. Then it is out of the valid values, the car will do a controlled breaking and then power off.
